language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yanivdror/docker-reaact -f Dockerfile.dev .

script:
  - docker run -e CI=true yanivdror/docker-react npm run test
